### ISSUE TITLE
This is a trojan

### ISSUE THREAD

**Issue by cl4Dev** [X9VoiD/WinUSBCleanup#2]
I recently ran this on my pc like 2 weeks ago, and today it got flagged by windows antivirus saying it was a Trojan being capable of remote controlling my pc, it detected and deleted everything in the folder. Don't install this. Better safe than sorry

**Comment by X9VoiD** [comment]
No, that's a false positive. What the script does is completely open source and human-readable. You can just verify yourself what it's doing. The binary files are directly from OEMs and are code signed.

**Comment by cl4Dev** [comment]
Yeah i also thought it was weird because it was open source xD But thanks for making me feel safe.
